
spring:
    datasource:
        url: jdbc:sqlite::resource:freestyle.db
        username:
        password:
        driver-class-name: org.sqlite.JDBC
        type: com.zaxxer.hikari.HikariDataSource
